# Site settings
author: fortuitous-dispatch-6424
title: 
header-img: img/home-bg.png
email: tanisha_henry28@hotmail.com
copyright_name: fortuitous-dispatch-6424
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Bluleo28

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
